version: '3.7'

services:
  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    # 連到mysql容器
      - mysql 
    ports:
      - "8181:80" 
    environment:
      PMA_HOST: mysql
      # （看不懂）Use MySQL root password for PHPMyAdmin
      MYSQL_ROOT_PASSWORD: password 
      
  # MySQL Service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: library_system
      MYSQL_USER: wys899195
      MYSQL_PASSWORD: wwww
    volumes:
    # mysql容器的資料庫內容備份到專案底下的mysql-data資料夾
      - ./mysql-backup-data:/var/lib/mysql
    # 自動匯入sql檔(確保table跟column沒有缺失)
      - ./library_system.sql:/docker-entrypoint-initdb.d/library_system.sql

  # library_system_service
  library_system_service:
    build: ./app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app/
    ports:
      - "8180:8000" 
    environment:
      - PYTHONDONTWRITEBYTECODE=1 # 讓它不要生__pycache__檔案

volumes:
  postgres_data_cast: