apiVersion: v1
kind: Service
metadata:
  name: library-system
  labels:
    app: library-system
    service: library-system
spec:
  ports:
  - port: 8180
    targetPort: 80
    name: http
  selector:
    app: library-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: library-system
  labels:
    account: library-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-system-v1
  labels:
    app: library-system
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-system
      version: v1
  template:
    metadata:
      labels:
        app: library-system
        version: v1
    spec:
      serviceAccountName: library-system
      containers:
      - name: library-system-container
        image: wys899195/fastapi_library_system_frontend:latest
        ports:
          - containerPort: 80
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
---
















