apiVersion: v1
kind: Service
metadata:
  name: collection-service
  labels:
    app: collection-service
    service: collection-service
spec:
  type: NodePort
  selector:
    app: collection-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30053

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collection-service
  labels:
    account: collection-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection-service-v1
  labels:
    app: collection-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collection-service
      version: v1
  template:
    metadata:
      labels:
        app: collection-service
        version: v1
    spec:
      serviceAccountName: collection-service
      containers:
        # 服務本體的容器
        - name: collection-service-container
          image: wys899195_library/collection_service:latest
          imagePullPolicy: Never
          command: 
            - "/bin/sh"
            - "-c"
            - >
              uvicorn main:app --reload --host 0.0.0.0 --port 8000
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              value: mysql  
            - name: MYSQL_PORT
              value: "3306" 
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
---